### ISSUE TITLE
WARNING: THIS LOCKS ACCOUNTS

### ISSUE THREAD

**Issue by Dragon-Batch** [joaokristani/Discord-Server-Cloner-2x#4]
Maybe dont send a message everytime someone uses your tool. it can lock their account if they open it too many times.

**Comment by joaokristani** [comment]
It's a bit unlikely that this will happen, as my server requires various Discord authentications. For instance, if it's Discord ghost accounts that don't require an email and phone number, it's evident that Discord will block them for suspicious activity. However, if it's an account with all the necessary authentications, it's very unlikely that this will occur. But if your main concern is this, I already had something in mind, which is to ask for user authorization so that I can conduct my tests.

**Thank you for your concern, but all of this is part of a test I'm conducting and won't be permanent. Maybe it will be permanent, but as I say, it's just a test.**

**Comment by Dragon-Batch** [comment]
> It's a bit unlikely that this will happen, as my server requires various Discord authentications. For instance, if it's Discord ghost accounts that don't require an email and phone number, it's evident that Discord will block them for suspicious activity. However, if it's an account with all the necessary authentications, it's very unlikely that this will occur. But if your main concern is this, I already had something in mind, which is to ask for user authorization so that I can conduct my tests.
> 
> **Thank you for your concern, but all of this is part of a test I'm conducting and won't be permanent. Maybe it will be permanent, but as I say, it's just a test.**

or you could just not fucking send "Hello World" into channel 1173960818841354382 in your server EVERY TIME THE USER USES THE SCRIPT

**Comment by Squashycord** [comment]
![image_2024-03-05_135339818](https://github.com/joaokristani/Discord-Server-Cloner-2x/assets/134233114/774d923b-e5ad-4b7d-994f-8cf5e16396a8)

this u bro

**Comment by Dragon-Batch** [comment]
dont call me bro. were not friends plus your gae

**Comment by calebthecm** [comment]
it's a fucking token stealer
